### ISSUE TITLE
dependency num-bigint-dig has a future incompatibility issue

### ISSUE THREAD

**Issue by shi-yan** [caojen/google-oauth#22]
warning: the following packages contain code that will be rejected by a future version of Rust: num-bigint-dig v0.8.4
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`

num-bigint-dig v0.8.4
└── rsa v0.9.8
    └── google-oauth v1.11.3

**Comment by sergiomeneses** [comment]
Hi there, any advance about this?

**Comment by caojen** [comment]
I'm very sorry for the long delay in replying. I've noticed the issue and will try to fix it in the next few days.

**Comment by caojen** [comment]
I noticed that the root cause of the issue is `num-bigint-dig v0.8.4`, which is introduced by the `rsa v0.9.8` dependency. Previous versions used `rsa ^0.9`. I have now specified `rsa v0.9.9`, which uses `num-bigint-dig v0.8.6`.

You can try the new version `1.11.4`; in my local environment, this issue has been resolved.

**Comment by sergiomeneses** [comment]
still the same error, i think the version `v0.9.9` of `rsa`  [doesn't even exists ](https://github.com/RustCrypto/RSA/tree/v0.9.9)

**Comment by caojen** [comment]
> still the same error, i think the version `v0.9.9` of `rsa` [doesn't even exists ](https://github.com/RustCrypto/RSA/tree/v0.9.9)

It seems that it's published.
https://crates.io/crates/rsa/0.9.9
